sonar.projectKey=naukri
sonar.organization=YOUR_ORGANIZATION

sonar.sources=backend/src,frontend/src,electron
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/test-results/**,**/playwright-report/**

sonar.sourceEncoding=UTF-8
